---
- name: "install apache2"
  become: true
  become_method: sudo
  become_user: root
  apt: 
    name: ["apache2"]
    state: latest
    update_cache: yes

- name: "install index page"
  become: true
  become_method: sudo
  become_user: root
  copy: 
    src: index.html
    dest: /var/www/html/
    backup: yes