---
# Exercise for setting up a web server in an EC
- name: Exercise for setting up a web server in an EC 
  # hosts: ubuntu
  # Use the public IP if the VM is already created
  hosts: ec2-3-86-77-116.compute-1.amazonaws.com
  gather_facts: no
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  roles:
    - setup


- name: "hello world webbage"
  hosts: all
  gather_facts: no
  roles:
    - prepare
    - apache