---
# Exercise for setting up a web server in an EC
- name: Exercise for setting up a web server in an EC 
  # hosts: ubuntu
  # Use the public IP if the VM is already created
  hosts: all
  gather_facts: no
  user: root
  become: true
  become_method: sudo
  become_user: root
  check_mode: no
  roles:
    - setup


- name: "hello world webbage"
  hosts: all
  gather_facts: no
  roles:
    - prepare
    - apache