---
- name: "update apt packages"
  become: true
  become_method: sudo
  become_user: root
  apt:
    update_cache: true

- name: "remove dependencies no longer required"
  become: true
  become_method: sudo
  become_user: root
  apt: 
    autoremove: yes